import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Hire Engineers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin={0} />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet" />
      </Head>
      <div className="grid grid-cols-2 mx-20">
      <div className="mt-14">
        <h2 className="font-poppins py-2 font-bold max-w-fit text-5xl banner-gradient">Hire skilled engineers</h2>
        <h1 className="font-poppins font-bold text-5xl text-[#1A202C]">at zero cost</h1>
        <p className="text-xl my-12 font-light font-poppins text-[#1A202C]">Recruit the ideal candidate for your business needs with Skill-Lync, in a hassle-free way</p>
        <button className="bg-[#0a1931] text-xl font-poppins font-semibold tracking-[0.3px] text-white px-28 my-4 py-2.5 rounded-md hover:bg-[#21CDAA] transition-colors duration-5000">Hire from us</button>
        </div>
        <div className="m-12">
          <img className="rounded-lg cursor-pointer" src="/accelerateHeroImage.png" alt="meeting" />
        </div>
        </div>
        <div className="flex flex-1 justify-around px-20 py-16 space-x-24 bg-[#F5F9FF] border-b-2 shadow-sm">
          <div>
          <h2 className="text-4xl text-[#0A1931] font-poppins font-bold">1,000+</h2>
          <p className="text-base text-[#0A1931] font-poppins font-normal">engineers hired in
the last year</p>
          </div>
          <div>
          <h2 className="text-4xl text-[#0A1931] font-poppins font-bold">300+</h2>
          <p className="text-base text-[#0A1931] font-poppins font-normal">companies hiring
from us</p>
          </div>
          <div>
          <h2 className="text-4xl text-[#0A1931] font-poppins font-bold">10,000+</h2>
          <p className="text-base text-[#0A1931] font-poppins font-normal">engineers equipped
with job-ready skills</p>
          </div>
          <div>
          <h2 className="text-4xl text-[#0A1931] font-poppins font-bold">1 week</h2>
          <p className="text-base text-[#0A1931] font-poppins font-normal">express deployment of
engineers</p>
          </div>
        </div>
        <div className="my-20">
          <h1 className="mx-auto text-4xl font-poppins font-bold banner-gradient max-w-fit">Top industry players</h1>
          <h1 className="text-center text-4xl text-[#1A202C] font-poppins font-light">who have hired from Skill-lync</h1>
        </div>
        <div className="flex flex-1 flex-wrap space-x-14 mx-20 my-20 justify-between">
          <div className="w-28 my-auto">
            <img src="/companies/kpit.png" alt="kpit" />
          </div>
          <div className="w-28 my-auto">
            <img src="/companies/mahindraRise.png" alt="mahindraRise" />
          </div>
          <div className="w-28 my-auto">
            <img src="/companies/ola.png" alt="ola" />
          </div>
          <div className="w-28 my-auto">
            <img src="/companies/capgemini.png" alt="capgemini" />
          </div>
          <div className="w-28 my-auto">
            <img src="/companies/expleo.png" alt="expleo" />
          </div>
          <div className="w-28 my-auto">
            <img src="/companies/cyient.png" alt="cyient" />
          </div>
          <div className="w-28 my-auto">
            <img src="/companies/hcl.png" alt="hcl" />
          </div>
          <div className="w-28 my-auto">
            <img src="/companies/tata.jpeg" alt="tata" />
          </div>
          <div className="w-28 my-auto">
            <img src="/companies/techMahindra.png" alt="techMahindra" />
          </div>
          <div className="w-28 my-auto">
            <img src="/companies/renault.png" alt="renault" />
          </div>
          <div className="w-28 my-auto">
            <img src="/companies/continental.png" alt="continental" />
          </div>
          <div className="w-28 my-auto">
            <img src="/companies/tataelxsi.png" alt="tataelxsi" />
          </div>
          <div className="w-16 my-auto">
            <img src="/companies/zf.png" alt="zf" />
          </div>
          <div className="w-28 my-auto">
            <img src="/companies/sona.png" alt="sona" />
          </div>
        </div>
        <div className="bg-purple-900">
        <h1 className="text-4xl text-center text-white font-poppins font-bold p-14">Here's what our corporate partners say</h1>
        <p className="text-white">We are glad to partner with Skill-Lync for upskilling technical knowledge of our employees in key areas like vehicle development including electrification and software helping us deliver products and services to our customers, global and local.</p>
        </div>

        {/* <div className="flex h-10 w-[500px] flex-1">
        <div className="w-[50%] bg-green-500"></div>
        <div className="w-[20%] bg-blue-500"></div>
        <div className="w-[30%] bg-pink-500"></div>
      </div> */}
    </>
  )
}
